pipeline:
  compile:
    image: ubuntu_16.04:salmon_build
    commands:
      - printf "Hello\n"
      - sleep 10
      - printf "Good bye\n"
      - echo "HELLO"
      - echo "PLEASE HELP"
      - echo `pwd`
      - ./.drone/build.sh
    notify:
      email:
        recipients:
          - combinelab.sbu@gmail.com
    
