sudo: false
language: cpp

matrix:
  include:
    - os : linux
      compiler : gcc-7
      addons:
        apt:
          update: true
          sources:
              - sourceline: 'ppa:mhier/libboost-latest'
              - ubuntu-toolchain-r-test
          packages: ['g++-7', 'gcc-7', 'zlib1g-dev', 'libbz2-dev']

install:
    - export CXX="g++-7"
    - export CC="gcc-7"
    - mkdir -p latest-gcc-symlinks
    - ln -s /usr/bin/g++-7 latest-gcc-symlinks/g++
    - ln -s /usr/bin/gcc-7 latest-gcc-symlinks/gcc
    - export PATH=$PWD/latest-gcc-symlinks:$PATH
    - export AR=gcc-ar-7
    - export RANLIB=gcc-ranlib-7
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - travis_retry wget --no-check-certificate https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.tar.gz
    - tar -xzvf cmake-3.12.0-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.12.0-Linux-x86_64 cmake-install
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    - cd ${TRAVIS_BUILD_DIR}
    
script: 
    - mkdir build 
    - cd build 
    - cmake -DFETCH_BOOST=TRUE -DNO_RTM=TRUE .. 
    - travis_wait 45 make 
    - travis_wait make install
    - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib:$LD_LIBRARY_PATH
    - travis_wait make test VERBOSE=1

after_success: 
    - cd $TRAVIS_BUILD_DIR
    - ./scripts/push-binary.sh
      
after_failure:
    - echo "Failure"
    - ls -laR $TRAVIS_BUILD_DIR/build/Testing/
    - cat $TRAVIS_BUILD_DIR/build/Testing/Temporary/*

#whitelist
#sudo: required
#dist: precise
#
#branches:
#    only:
#        - master
#        - develop
#
#language: cpp
#
#compiler: gcc
#
#addons:
#  apt:
#    sources:
#      - boost-latest
#      - kalakris-cmake
#      - ubuntu-toolchain-r-test
#      - george-edison55-precise-backports
#    packages:
#      - cmake
#      - cmake-data
#      - gcc-4.9
#      - g++-4.9
#
#before_install:
##    - echo "yes" | sudo apt-add-repository ppa:boost-latest
##    - echo "yes" | sudo apt-add-repository ppa:mapnik/boost-backports-1-54
##    - echo "yes" | sudo apt-add-repository ppa:h-rayflood/gcc-upper
##    - echo "yes" | sudo add-apt-repository ppa:george-edison55/precise-backports
##    - sudo apt-get clean -qq
##    - sudo apt-get update -qq
##    - sudo apt-mark showhold -qq
##    - sudo apt-get install -qq cmake
##    - sudo apt-get install -qq gcc-4.9 g++-4.9 
#    - export CC="gcc-4.9"
#    - export CXX="gcc-4.9"
#    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
#    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
#
#install:
#    - export CXX="g++-4.9"
#    - export CC="gcc-4.9"
#
#script: 
#    - mkdir build 
#    - cd build 
#    - cmake -DCONDA_BUILD=TRUE -DFETCH_BOOST=TRUE -DNO_RTM=TRUE .. 
#    - travis_wait 45 make 
#    - travis_wait make install
#    - travis_wait make test VERBOSE=1
#
#after_success: 
#    - cd $TRAVIS_BUILD_DIR
#    - ./scripts/push-binary.sh
#      
#after_failure:
#    - cat $TRAVIS_BUILD_DIR/build/Testing/Temporary/LastTest.log
